name: Smart Itinerary Preview Deployment

env:
    AIKIDO_CI_KEY: ${{ secrets.AIKIDO_SECRET_KEY }}
    GH_KEY: ${{ secrets.GH_SMART_TOKEN }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
    NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
    NEXT_PUBLIC_ENABLE_MOCK_AUTH: true

on:
    pull_request:
        branches:
            - develop
        paths-ignore:
            - 'README.md'

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: 20.x
    
          - run: npm ci
    
          - run: npm run build

    Test:
        needs: [Build]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-node@v4
            with:
              node-version: 20.x

          - run: npm ci

          - name: Run Cypress Component Tests
            run: npm run component:headless

          - name: Build app
            run: npm run build

          - name: Run Cypress E2E tests
            uses: cypress-io/github-action@v6
            with:
              start: npm run start
              wait-on: 'http://localhost:3000'
              wait-on-timeout: 60
              command: npm run e2e:headless
            env:
              NEXT_PUBLIC_ENABLE_MOCK_AUTH: true
              NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
              NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
              NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          
          - name: Upload screenshots
            uses: actions/upload-artifact@v4
            if: failure()
            with:
              name: cypress-screenshots
              path: cypress/screenshots

    SAST:
        needs: [Test]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Detect new vulnerabilities
          uses: AikidoSec/github-actions-workflow@v1.0.13
          with:
              secret-key: ${{ env.AIKIDO_CI_KEY }}
              fail-on-timeout: true
              fail-on-dependency-scan: true
              fail-on-sast-scan: false
              fail-on-iac-scan: false
              minimum-severity: 'CRITICAL'
              timeout-seconds: 180
              post-scan-status-comment: 'off'
              post-sast-review-comments: 'off'
              github-token: ${{ env.GH_KEY }}

    Deploy-Preview:
        needs: [SAST]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ env.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}